
# ------------------
#      General
# ------------------

# Whether to expect a bungee instance to interact with. This is used to
# fix several issues inherit with using using this plugin on BungeeCord
# servers.
bungee-forward: false

# The index to start allocating map IDs at. Most of the time, you will
# not need to touch this variable, however, if you are running servers
# with more than one isntance of the consoles plugin, it is suggested
# to give a new index (about 10,000 larger).
#
# Do not set this variable close to 65536, as it could cause constant
# client disconnects if there are a lot of consoles in your server.
starting-map-index: 5000

# Debug mode. Useful for developers, this option will print stack traces
# for every runtime Lua program crash (showing internal stack traces), and
# various information about computer data saving/loading along with other
# odds and ends.
#
# If you think there is something wrong with a Lua function call into
# Consoles, you can enable this to get the full stack trace.
debug-mode: false