
# ------------------
#      General
# ------------------

# Whether to expect a bungee instance to interact with. This is used to
# manage per-player map ID allocations to avoid maps locking up and failing
# to update.
bungee-forward: false

# ------------------
#     Computers
# ------------------

# Enable the crafting of computers
allow-comptuer-crafting: true

# Computer crafting limit for normal players
# The permissions computer.limit.ignore will override this
computer-limit: 3

# ------------------
# Computer Functions
# ------------------

# Advanced component rendering, but insecure and exposes the consoles API to Lua code
custom-components: false

# Custom frame rendering, much safer (and easier) alternative to the above, but slower and less responsive.
frame-rendering: true

# Maximum time (in miliseconds) that a program can run without calling a blocking function
# You can tweak this to be lower if you want to avoid program threads from using too
# many server resources.
max-time-without-interrupt: 7000