
# ------------------
#      General
# ------------------

# Whether to expect a bungee instance to interact with. This is used to
# fix several issues inherit with using using this plugin on BungeeCord
# servers.
bungee-forward: false

# The index to start allocating map IDs at. Most of the time, you will
# not need to touch this variable, however, if you are running servers
# with more than one isntance of the consoles plugin, it is suggested
# to give a new index (about 10,000 larger).
#
# Do not set this variable close to 65536, as it could cause constant
# client disconnects if there are a lot of consoles in your server.
starting-map-index: 5000


# ------------------
#     Computers
# ------------------

# Enable comptuers. If disabled, all computer-related computer functionality
# will be disabled. Useful if you only want to use Consoles for its API.
enable-computers: true

# Enable the crafting of computers
allow-comptuer-crafting: true

# Computer crafting limit for normal players
# The permissions computer.limit.ignore will override this
computer-limit: 3

# Command prefix when sending commands to a computer. You may want to
# change this for BungeeCord servers, as it will interrupt commands
# that may have been designated for a computer.
command-prefix: /

# ------------------
# Computer Functions
# ------------------

# Advanced component rendering, but insecure and exposes the consoles API to Lua code
custom-components: false

# Custom frame rendering, much safer (and easier) alternative to the above, but slower and less responsive.
frame-rendering: true

# Maximum time (in miliseconds) that a program can run without calling a blocking function
# You can tweak this to be lower if you want to avoid program threads from using too
# many server resources.
max-time-without-interrupt: 7000